version: "3.9"

services:
  app:
    image: ghcr.io/ShareTheWorld/beany:latest
    container_name: beany-fastapi-async
    ports:
      - "8000:8000"
    env_file:
      - /data/services/beany-fastapi-async/.env
    restart: always
